### ISSUE TITLE
Shader Support

### ISSUE THREAD

**Issue by belohlavek** [coding-jackalope/Slab#8]
What do you think abount having a Draw Shader command?

I enabled them for my own app by doing something like this:

```lua
local function DrawShader(Opts)
    local StatHandle = Stats.Begin("DrawShader", StatsCategory)

    if Opts.Fragment ~= nil then
        local shader = love.graphics.newShader(Opts.Fragment)
        for k, v in pairs(Opts.Values) do
            shader:send(k, v)
        end
        love.graphics.setShader(shader)
    else
        love.graphics.setShader()
    end

    Stats.End(StatHandle)
end
```

This is my first time using Lua/Love2D, and also using an ImGUI so I don't really know if this is an anti pattern. Could you give me some feedback?

On top of my head I'm guessing that the shader should only be created once and reused/disposed

**Comment by flamendless** [comment]
Youre calling newShader every frame? That's not good.

**Comment by belohlavek** [comment]
@flamendless I know, right?!
What's the best way to go about this? A table and some caching strategy?

**Comment by flamendless** [comment]
Why not create the shader object in love.load? You can use a local or global variable for that, so you can reference that in the draw method. Kinda like

```lua
local shader
function love.load()
  shader = love.graphics.newShader("pathtoshader")
  Slab.initialize()
end

function love.update(dt)
  --call your slab drawings
end
```

**Comment by belohlavek** [comment]
AFAIK all `love.graphics` calls should go inside a Slab's DrawCommand
Having said that, yes, it does make sense for the app itself to handle storing the shaders rather than the library.  I'll go that way, thanks ;)

**Comment by flamendless** [comment]
Well yeah, love.graphics call should go to love.draw (unless you're drawing in a canvas, in which case you could do it even in love.load and love.update)

So, draw Slab in update, applying shaders is in draw

**Comment by belohlavek** [comment]
Sorry if I wasn't clear enough, I'm applying shaders to Slab widgets. It is true that shading should happen in `love.draw` but the correct way to impact, say, a Slab.Image would be (as far as I know, remember I'm a newbie 😄) to do it inside a DrawCommand. See https://github.com/coding-jackalope/Slab/blob/master/Internal/Core/DrawCommands.lua

I'm not creating a game and I am making an extensive use of Slab's layering and layout system. There's little benefit for my use case to do anything inside `love.draw` as I need to reset the shader once the draw widget command is done, so I only need to call Slab.draw at that point!

**Comment by coding-jackalope** [comment]
Hi @belohlavek , this would definitely be a useful feature to have. I'll be sure to add this as a feature item for an upcoming release.

My recommendation would be to create your shader object in love.load and store it within your application somewhere. Then when calling Slab.Image in your update loop, pass the shader object in with the Options table. Then inside of Image.Begin, the shader object should then be passed into the DrawCommands.Image Options table. Then you can set the shader appropriately inside of the DrawImage function in DrawCommands.lua. This would be a quick way for you to get custom shaders working for images.

I'll be looking into something more versatile when I implement this so that it can be supported for all primitives. Hope this helps.

**Comment by belohlavek** [comment]
Awesome, that's exactly what I have implemented right now!

Thanks both of you @coding-jackalope @flamendless
