### ISSUE TITLE
File dialog tree: collapse parent folders

### ISSUE THREAD

**Issue by belohlavek** [coding-jackalope/Slab#9]
It seems like it's not possible to collapse parent folders on the file dialog tree view
Tested on windows 10

![Fk2RhjuTWt](https://user-images.githubusercontent.com/1307029/77831316-28b9cc00-710d-11ea-8e9d-d44c2935f3d3.gif)

@coding-jackalope if you don't know what could cause this I can look into it in the coming days and send a PR, as I need to fix it for my app :)

**Comment by coding-jackalope** [comment]
Yes, this was intentionally programmed in when the file dialog was implemented. This line in particular is the culprit inside of FileDialogExplorer:

```lua
local ShouldOpen = string.find(Instance.Directory, Root.Path, 1, true) ~= nil
```

The proper way of doing this is to only pass the IsOpen option when the dialog first appears so that the tree expands to the proper location. The Dialog.FileDialog function already knows if the dialog was open in the last frame. This flag needs to be passed into the FileDialogExplorer function and the IsOpen option should be set to:

```lua
IsOpen = not WasOpen and string.find(Instance.Directory, Root.Path, 1, true) ~= nil
```

You should be able to make these changes locally for your application. I do, however, plan on a release for a small update within the next few days that uses the lovefs library. This is a much safer method of querying the file system instead of the current method of using io.popen to make system calls. I'll have a fix for this in that update.

**Comment by belohlavek** [comment]
Sounds great, awesome work :)

**Comment by coding-jackalope** [comment]
Hi @belohlavek, I just pushed an update with a fix for this. Whenever you get a chance, try it out and let me know if this issue is resolved on your end.

**Comment by belohlavek** [comment]
Seems to function well, but the aligment seems to break when opening some folders
![dgVwTY4htM](https://user-images.githubusercontent.com/1307029/77864984-5896cb80-7202-11ea-8730-affd51681488.gif)

**Comment by coding-jackalope** [comment]
This seems to be an existing issue with how trees are handled. I will go ahead and close this issue and open another for this specific case.
